services:
  - type: web
    name: mosaad
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/settings
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: SESSION_SECRET
        generateValue: true
      - key: WHATSAPP_NUMBER
        value: "79990000000"
